# Generated by Django 5.0.7 on 2024-08-07 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_end_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='buy_it_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 13, 55, 38, 668345, tzinfo=datetime.timezone.utc)),
        ),
    ]
