# Generated by Django 5.0.7 on 2024-08-07 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_buy_it_now_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 14, 13, 10, 314834, tzinfo=datetime.timezone.utc)),
        ),
    ]
