# Generated by Django 5.0.7 on 2024-08-07 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 14, 45, 26, 9445, tzinfo=datetime.timezone.utc)),
        ),
    ]
