# Generated by Django 5.0.7 on 2024-08-07 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 15, 14, 23, 31011, tzinfo=datetime.timezone.utc)),
        ),
    ]
