# Generated by Django 5.0.7 on 2024-08-07 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_payment_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 15, 29, 50, 386303, tzinfo=datetime.timezone.utc)),
        ),
    ]
