# Generated by Django 5.0.7 on 2024-08-08 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_message_is_system_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 20, 35, 2, 370851, tzinfo=datetime.timezone.utc)),
        ),
    ]
