# Generated by Django 5.0.7 on 2024-08-11 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 22, 10, 58, 635750, tzinfo=datetime.timezone.utc)),
        ),
    ]
