# Generated by Django 5.0.7 on 2024-08-12 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 2, 42, 41, 345197, tzinfo=datetime.timezone.utc)),
        ),
    ]
