# Generated by Django 5.0.7 on 2024-08-12 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_alter_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 22, 29, 51, 454884, tzinfo=datetime.timezone.utc)),
        ),
    ]
